spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_order?useSSL=false&requireSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    tomcat:
      max-wait: 10000
      min-idle: 0
      initial-size: 25
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
      remove-abandoned: true
      remove-abandoned-timeout: 180